// configs/appliances.js
// Pure data. No Three.js imports. Each entry defines one appliance.
import { LightTokens as L } from '../tokens/lights.js';

export const ApplianceConfigs = [
  // ========== LIVING ROOM ==========
  {
    id: 'tv',
    name: 'TV',
    room: 'LIV',
    kind: 'screen',
    geometry: 'tv',
    materials: { frame: 'blackPlastic', screen: 'screenOn', stand: 'darkGray' },
    behaviors: [{ type: 'emissive', target: 'screen' }],
    light: null,
    position: [0, 1.6, -1.75],
    rotation: 0,
  },
  {
    id: 'ceilingFanLiv',
    name: 'Kipas Siling (Ruang Tamu)',
    room: 'LIV',
    kind: 'fan-light',
    geometry: 'ceilingFan',
    materials: { mount: 'darkGray', blades: 'lightWood', lampDome: 'warmGlow' },
    behaviors: [
      { type: 'spin', target: 'rotor', speed: 7 },
      { type: 'emissive', target: 'lampDome' },
      { type: 'light' },
    ],
    light: { ...L.warmCeiling, offset: [0, -0.3, 0] },
    position: [0, 2.75, 5],
    rotation: 0,
  },
  {
    id: 'standingLamp',
    name: 'Lampu Berdiri',
    room: 'LIV',
    kind: 'lamp',
    geometry: 'standingLamp',
    materials: { base: 'darkGray', pole: 'darkCharcoal', shade: 'warmGlowCone' },
    behaviors: [
      { type: 'emissive', target: 'shade' },
      { type: 'light' },
    ],
    light: { ...L.warmLamp, offset: [0, 1.4, 0] },
    position: [-4.2, 0.03, 1.5],
    rotation: 0,
  },
  {
    id: 'router',
    name: 'Wi-Fi Router',
    room: 'LIV',
    kind: 'gadget',
    geometry: 'router',
    materials: { body: 'blackPlastic' },
    behaviors: [],
    light: null,
    position: [-4.2, 0.62, -1.4],
    rotation: 0,
  },
  {
    id: 'speaker',
    name: 'Speaker',
    room: 'LIV',
    kind: 'gadget',
    geometry: 'speaker',
    materials: { body: 'darkGray', cone: 'blackPlastic' },
    behaviors: [],
    light: null,
    position: [4.2, 0.4, -1.5],
    rotation: 0,
  },
  {
    id: 'playstation',
    name: 'PlayStation',
    room: 'LIV',
    kind: 'gadget',
    geometry: 'console',
    materials: { body: 'whitePlastic' },
    behaviors: [],
    light: null,
    position: [-0.7, 0.61, -1.5],
    rotation: 0,
  },

  // ========== KITCHEN ==========
  {
    id: 'fridge',
    name: 'Peti Sejuk',
    room: 'KIT',
    kind: 'big',
    geometry: 'fridge',
    materials: { body: 'offWhite', seam: 'lightGray', handle: 'grayPlastic' },
    behaviors: [],
    light: null,
    position: [-6.5, 0, 0.8],
    rotation: 0,
  },
  {
    id: 'microwave',
    name: 'Microwave',
    room: 'KIT',
    kind: 'gadget',
    geometry: 'microwave',
    materials: { body: 'darkGray', door: 'tintedGlass' },
    behaviors: [],
    light: null,
    position: [-13.6, 1.22, 8],
    rotation: 0,
  },
  {
    id: 'riceCooker',
    name: 'Periuk Nasi',
    room: 'KIT',
    kind: 'gadget',
    geometry: 'riceCooker',
    materials: { body: 'whitePlastic', lid: 'aluminum' },
    behaviors: [],
    light: null,
    position: [-13.6, 1.16, 6],
    rotation: 0,
  },
  {
    id: 'kettle',
    name: 'Cerek',
    room: 'KIT',
    kind: 'gadget',
    geometry: 'kettle',
    materials: { body: 'stainless', spout: 'darkGray', handle: 'darkGray' },
    behaviors: [],
    light: null,
    position: [-13.6, 1.15, 4.4],
    rotation: 0,
  },
  {
    id: 'toaster',
    name: 'Toaster',
    room: 'KIT',
    kind: 'gadget',
    geometry: 'toaster',
    materials: { body: 'brushedSteel', slot: 'blackPlastic' },
    behaviors: [],
    light: null,
    position: [-13.6, 1.13, 3],
    rotation: 0,
  },
  {
    id: 'ceilingLightKit',
    name: 'Lampu Siling (Dapur)',
    room: 'KIT',
    kind: 'ceiling-light',
    geometry: 'ceilingLightSquare',
    materials: { panel: 'ceilingWarm' },
    behaviors: [
      { type: 'emissive', target: 'panel' },
      { type: 'light' },
    ],
    light: { ...L.kitchenCeiling, offset: [0, -0.2, 0] },
    position: [-10, 2.92, 5],
    rotation: 0,
  },

  // ========== DINING ==========
  {
    id: 'waterDispenser',
    name: 'Penyejuk Air',
    room: 'DIN',
    kind: 'big',
    geometry: 'waterDispenser',
    materials: { body: 'offWhite', tank: 'clearBlue', tap: 'darkCharcoal' },
    behaviors: [],
    light: null,
    position: [14, 0, 11],
    rotation: 0,
  },
  {
    id: 'ceilingFanDin',
    name: 'Kipas Siling (Ruang Makan)',
    room: 'DIN',
    kind: 'fan-light',
    geometry: 'ceilingFan',
    materials: { mount: 'darkGray', blades: 'lightWood', lampDome: 'warmGlow' },
    behaviors: [
      { type: 'spin', target: 'rotor', speed: 6.5 },
      { type: 'emissive', target: 'lampDome' },
      { type: 'light' },
    ],
    light: { ...L.warmCeiling, offset: [0, -0.3, 0] },
    position: [10, 2.75, 5],
    rotation: 0,
  },

  // ========== BEDROOM 1 ==========
  {
    id: 'aircondBr1',
    name: 'Aircond (Bilik 1)',
    room: 'BR1',
    kind: 'big',
    geometry: 'aircond',
    materials: { body: 'whitePlastic', vent: 'lightGray' },
    behaviors: [],
    light: null,
    position: [-10, 2.4, -11.7],
    rotation: 0,
  },
  {
    id: 'bedsideLamp',
    name: 'Lampu Tepi Katil',
    room: 'BR1',
    kind: 'lamp',
    geometry: 'bedsideLamp',
    materials: { base: 'darkCharcoal', pole: 'grayPlastic', shade: 'warmGlowBright' },
    behaviors: [
      { type: 'emissive', target: 'shade' },
      { type: 'light' },
    ],
    light: { ...L.warmLampSmall, offset: [0, 0.3, 0] },
    position: [-10, 0.83, -9.5],
    rotation: 0,
  },
  {
    id: 'phoneCharger',
    name: 'Charger Telefon',
    room: 'BR1',
    kind: 'small',
    geometry: 'phoneCharger',
    materials: { block: 'whitePlastic', phone: 'blackPlastic' },
    behaviors: [],
    light: null,
    position: [-10, 0.83, -9.7],
    rotation: 0,
  },
  {
    id: 'standingFan',
    name: 'Kipas Berdiri',
    room: 'BR1',
    kind: 'fan',
    geometry: 'standingFan',
    materials: { base: 'darkGray', pole: 'medGray', cage: 'grayPlastic', blades: 'lightGray' },
    behaviors: [{ type: 'spin', target: 'rotor', speed: 10 }],
    light: null,
    position: [-7.2, 0.03, -4],
    rotation: 0,
  },
  {
    id: 'ceilingLightBr1',
    name: 'Lampu Siling (Bilik 1)',
    room: 'BR1',
    kind: 'ceiling-light',
    geometry: 'ceilingLightRound',
    materials: { panel: 'ceilingNeutral' },
    behaviors: [
      { type: 'emissive', target: 'panel' },
      { type: 'light' },
    ],
    light: { ...L.bedroomCeiling, offset: [0, -0.2, 0] },
    position: [-10, 2.92, -7],
    rotation: 0,
  },

  // ========== BEDROOM 2 ==========
  {
    id: 'aircondBr2',
    name: 'Aircond (Bilik 2)',
    room: 'BR2',
    kind: 'big',
    geometry: 'aircond',
    materials: { body: 'whitePlastic', vent: 'lightGray' },
    behaviors: [],
    light: null,
    position: [10, 2.4, -11.7],
    rotation: 0,
  },
  {
    id: 'computerMonitor',
    name: 'Monitor Komputer',
    room: 'BR2',
    kind: 'screen',
    geometry: 'computerMonitor',
    materials: { stand: 'darkGray', frame: 'blackPlastic', screen: 'screenOnAlt' },
    behaviors: [{ type: 'emissive', target: 'screen' }],
    light: null,
    position: [8, 1.05, -4],
    rotation: 0,
  },
  {
    id: 'deskLamp',
    name: 'Lampu Meja',
    room: 'BR2',
    kind: 'lamp',
    geometry: 'deskLamp',
    materials: { base: 'darkGray', arm: 'darkCharcoal', head: 'warmGlowCone' },
    behaviors: [
      { type: 'emissive', target: 'head' },
      { type: 'light' },
    ],
    light: { ...L.warmLampDesk, offset: [0.25, 0.3, 0] },
    position: [7.4, 1.03, -4.2],
    rotation: 0,
  },
  {
    id: 'ceilingLightBr2',
    name: 'Lampu Siling (Bilik 2)',
    room: 'BR2',
    kind: 'ceiling-light',
    geometry: 'ceilingLightRound',
    materials: { panel: 'ceilingNeutral' },
    behaviors: [
      { type: 'emissive', target: 'panel' },
      { type: 'light' },
    ],
    light: { ...L.bedroomCeiling, offset: [0, -0.2, 0] },
    position: [10, 2.92, -7],
    rotation: 0,
  },

  // ========== BATHROOM ==========
  {
    id: 'waterHeater',
    name: 'Pemanas Air',
    room: 'BATH',
    kind: 'big',
    geometry: 'waterHeater',
    materials: { body: 'whitePlastic', pipe: 'aluminum' },
    behaviors: [],
    light: null,
    position: [-4.5, 2.4, -10],
    rotation: 0,
  },
  {
    id: 'hairDryer',
    name: 'Pengering Rambut',
    room: 'BATH',
    kind: 'small',
    geometry: 'hairDryer',
    materials: { body: 'pinkPlastic' },
    behaviors: [],
    light: null,
    position: [3.5, 1.05, -4],
    rotation: 0,
  },
  {
    id: 'ceilingLightBath',
    name: 'Lampu Siling (Bilik Air)',
    room: 'BATH',
    kind: 'ceiling-light',
    geometry: 'ceilingLightRound',
    materials: { panel: 'ceilingCool' },
    behaviors: [
      { type: 'emissive', target: 'panel' },
      { type: 'light' },
    ],
    light: { ...L.bathCeiling, offset: [0, -0.2, 0] },
    position: [0, 2.93, -7],
    rotation: 0,
  },
];
